library_path = "/private/var/folders/fm/42rbhgsx5zbbdxd26mg_f36h0000gn/T/tmpaxwy1x94/lib"
download_path = "/private/var/folders/fm/42rbhgsx5zbbdxd26mg_f36h0000gn/T/pytest-of-G/pytest-11/test_save_and_reload_settings0/D1"
