library_path = "/private/var/folders/fm/42rbhgsx5zbbdxd26mg_f36h0000gn/T/tmp8rjn9re0/lib"
download_path = "/private/var/folders/fm/42rbhgsx5zbbdxd26mg_f36h0000gn/T/pytest-of-G/pytest-51/test_save_and_reload_settings0/D1"
